<?php
// Find me in /module/Notes/view/contacts/delete.phtml

$title = 'Contact#delete';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete:</p>
<table class="table">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>Surname</th>
    <th>Description</th>
    <th>Created At</th>
</tr>
    <tr>
        <td><?php echo $this->escapeHtml($contacts->contact_id);?></td>
        <td><?php echo $this->escapeHtml($contacts->contact_name);?></td>
        <td><?php echo $this->escapeHtml($contacts->contact_surname);?></td>
        <td><?php echo $this->escapeHtml($contacts->contact_description);?></td>
        <td><?php echo $this->escapeHtml($contacts->created_at);?></td>
    </tr>
</table>
<?php
$url = $this->url('contacts', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $contacts->contact_id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
