<?php
$title = 'My contacts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('contacts', array('action'=>'add'));?>">Add new contact</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Description</th>
</tr>
<?php foreach ($this->paginator as $record) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($record->contact_name);?></td>
        <td><?php echo $this->escapeHtml($record->contact_surname);?></td>
        <td><?php echo $this->escapeHtml($record->contact_description);?></td>
        <td>
            <a href="<?php echo $this->url('contacts', array('action'=>'edit', 'id' => $record->contact_id));?>">Edit</a>
            <a href="<?php echo $this->url('contacts', array('action'=>'delete', 'id' => $record->contact_id));?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<?php 
echo $this->paginationControl(
  $this->paginator,
  'sliding',
  array('partials/paginator.phtml', 'Contacts'),
  array(
    'route' => 'contacts'
  )
);
?>
