<?php 
$title = 'My calendar';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('calendar', array('action'=>'add'));?>">Add new event</a>
</p>
<table class="table">
<tr>
    <th>Created At</th>
</tr>
</table>
<?php
$dates = array();
foreach ($this->records as $record) 
{
  $dateTime = new DateTime($record->created_at);
  $date = $dateTime->format('n j'); 
  array_push($dates,$date);
} 
?> 
<ul class="calendar clearfix">
<?php foreach ($this->calendar as $day) : ?>
    <li>
<?php     if (in_array($day, $dates)) 
          {
            $a = '<a class="day event-set" href="'. $this->url('calendar', array('action'=>'edit')).'">'. $day  .'</a>';
            echo $a;
          } else { 
            $a = '<a class="day event-not-set" href="'. $this->url('calendar', array('action'=>'add')).'">'. $day .'</a>';
            echo $a;
          }
?>
    </li>
<?php endforeach; ?>
</ul>
