<?php 
$title = 'My calendar';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$dates = array();
foreach ($this->records as $record) 
{
  $dateTime = new DateTime($record->created_at);
  $date = $dateTime->format('Y-m-d'); 
  array_push($dates,$date);
}
$back = 1;
$forward = 1;
?>
<ul class="calendar clearfix">
  <li><a href='<?php echo $this->url('calendar', array('action'=>'index')).'?b='.$this->back.'&f='.$this->forward ?>'>Previous month</a></li>
<?php foreach ($this->calendar as $day) : ?>
    <li>
<?php     
$fullDay = $day[0].' '.$day[1];
$fullDayDash = $day[2].'-'.$day[1].'-'.$day[0];
$fullDayDashTime = new DateTime($fullDayDash);
$name = $fullDayDashTime->format('Y-m-d');
          if (in_array($name, $dates)) 
          {
            $a = '<a class="day event-set" href="'. $this->url('calendar', array('action'=>'edit', 'date' => $name)).'">'. $fullDay  .'</a>';
            echo $a;
          } else { 
            $a = '<a class="day event-not-set" href="'. $this->url('calendar', array('action'=>'add', 'date' => $name)).'">'. $fullDay .'</a>';
            echo $a;
          }
?>
    </li>
<?php endforeach; ?>
  <li><a href='<?php echo $this->url('calendar', array('action'=>'index')).'?b='.$this->back.'&f='.$this->forward ?>'>Next month</a></li>
</ul>
