<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Personal information manager'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/my.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-social.css')
                        ->prependStylesheet($this->basePath() . '/css/flat-ui.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Personal information manager') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
<?php
  if (!$this->zfcUserIdentity()) { 
?>
                        <li><a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Sign in') ?></a></li>
                        <li><a href="<?php echo $this->url('zfcuser/register') ?>"><?php echo $this->translate('Register') ?></a></li>
<?php } else { ?>
<?php if ($this->zfcUserIdentity()->getId() == 2) { 
?>
                        <li><a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate('Admin Panel') ?></a></li>
<?php } ?>
                       <!-- <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Overview') ?></a></li>-->
                        <li><a href="<?php echo $this->url('notes') ?>"><?php echo $this->translate('Notes') ?></a></li>
                        <li><a href="<?php echo $this->url('contacts') ?>"><?php echo $this->translate('Contacts') ?></a></li>
                        <li><a href="<?php echo $this->url('calendar') ?>"><?php echo $this->translate('Calendar') ?></a></li>
                        <li><a href="<?php echo $this->url('zfcuser') ?>" class="gravatar profile-photo"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></a></li>
                        <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sign out') ?></a></li>
<?php } ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; since 2014 | by Marcin Ziółek <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
