<?php
$title = 'My notes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('notes', array('action'=>'add'));?>">Add new record</a>
</p>
<ul class="notes col-md-12 clearfix">
<?php foreach ($this->paginator as $record) : ?>
    <li class="col-md-3">
      <div>
        <h4><?php echo $this->escapeHtml($record->note_title);?></h4>
        <p><?php echo $this->escapeHtml($record->note_body);?></p>
        <p><b>Last update:</b></p>
        <p><?php echo $this->escapeHtml($record->created_at);?></p>
        <p class="edit-delete">
            <a class="btn btn-block btn-lg btn-inverse" href="<?php echo $this->url('notes', array('action'=>'edit', 'id' => $record->note_id));?>">Edit</a>
            <a class="btn btn-block btn-lg btn-danger" href="<?php echo $this->url('notes', array('action'=>'delete', 'id' => $record->note_id));?>">Delete</a>
        </p>
      </div>
    </li>
<?php endforeach; ?>
</ul>
<?php 
echo $this->paginationControl(
  $this->paginator,
  'sliding',
  array('partials/paginator.phtml', 'Notes'),
  array(
    'route' => 'notes'
  )
);
?>
