<?php
$title = 'Admin panel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
<tr>
    <th>Id</th>
    <th>Email</th>
    <th>Display name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $record) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($record->user_id);?></td>
        <td><?php echo $this->escapeHtml($record->email);?></td>
        <td><?php echo $this->escapeHtml($record->display_name);?></td>
        <td>
            <a href="<?php echo $this->url('admin', array('action'=>'delete', 'id' => $record->user_id));?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>



<?php echo $this->paginationControl(
    $this->paginator,
    'sliding',
    array('partials/paginator.phtml', 'Admin'),
    array(
        'route' => 'admin'
    )
); ?>



